### ISSUE TITLE
Need to add option for message exactly match in class MessageSystemCallItem in device/system_call_manager.py

### ISSUE THREAD

**Issue by qilinkang** [openthread/silk#62]
The message check In method invoke() is:

 match = re.search(self.expect, response)

        if match is None:
            self.log_match_failure(response)
            return

For Thread traffic test cases we need to add exactly match check between the sending and received data .

**Comment by tzm41** [comment]
Some commands append EOL char to output. Should we do `rstrip()` to remove spaces and `\n`?

**Comment by qilinkang** [comment]
Doing rstrip() looks good.
